# Site settings
title: Interactive Wearable Backpack Workshop 
email: info@fablabtorino.org
url: https://example.github.io
description: "This is the project page of a introductive wearable computing workshop held in beginning 2015 at FablabTorino, Italy"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Visualization mode: here you can chose the visualization of your posts; write grid if you want a grid layout; write blog if you want a blog-style layout. if you don't want do show this section write none. !!modify href on navbar tab "post" in nav.html
visualization: post

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Fablab Torino 
  location: Turin
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: The Internet
    url: http://fablabtorino.org/
  - title: twitter
    url: https://twitter.com/fablabtorino
  - title: facebook
    url:https://www.facebook.com/fablabtorino
  - title: github
    url: https://github.com/fablabTorino
  - title: youtube
    url: https://www.youtube.com/user/ItalianFabLab
  - title: Thingiverse
    url: http://www.thingiverse.com/FablabTorino/designs

# Postal address (add as many lines as necessary)
address:
  - line: Via Egeo 16, Torino

# Credits content
credits: 'Based on Freelancer, adapted by Ale Gueli for Officine Arduino / FablabTorino'

# Build settings
markdown: kramdown
permalink: pretty
